language: node_js
node_js:
  - 14  
deploy:
  provider: releases
  api_key: "d73851db70a0e7f175332661a7064c4d617afc1d"
  file_glob: true
  file: src/*
  skip_cleanup: true
  on:
    tags: true
    all_branches: true

script: 'true'

before_install:
  - npm i -g npm@6.14.9
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.1.0
  - export PATH="$HOME/.yarn/bin:$PATH"
  - sudo apt-get update
  - sudo apt-get -y install libxml2-dev

cache:
  yarn: true

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8