GET http://localhost:3000
#####getallfriend
GET http://localhost:3000/friend/


GET http://localhost:3000/post/




####1. linkfriends
PUT http://localhost:3000/friend/linkup
Content-Type: application/json

{
  "emails": [
    "test@gmail.com",
    "john9@example.com"
  ]
}


####2. get all friends
GET http://localhost:3000/friend/allFriends/test1@gmail.com


####3. common friends
POST http://localhost:3000/friend/commonFriends
Content-Type: application/json

{
  "emails": [
    "test@gmail.com",
    "test1@gmail.com"
  ]
}

####4. subscribe
PUT http://localhost:3000/friend/subscribe
Content-Type: application/json

{
  "emails": [
    "test@gmail.com",
    "john9@example.com"
  ]
}



####5. block
PUT http://localhost:3000/friend/block
Content-Type: application/json

{
  "emails": [
    "test@gmail.com",
    "john9@example.com"
  ]
}


####6. get all subscribed emails
GET http://localhost:3000/friend/allSubList/test1@gmail.com


#### get post by email
GET http://localhost:3000/post/allposts/test1@gmail.com
